apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-proyecto-tolerante
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto-tolerante
  template:
    metadata:
      labels:
        app: proyecto-tolerante
    spec:
      containers:
      - name: proyecto-tolerante-container
        image: ccisaias/proyecto-tolerante
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000